version: '3.7'
services:
  proxy:
    container_name: cat-pinterest-proxy
    image: nginx:1.24-alpine-slim
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    depends_on:
      cat-pinterest-api:
        condition: service_started
    ports:
      - "8080:80"
    networks:
      - cat-pinterest-net

  cat-pinterest-api:
    container_name: cat-pinterest-api
    image: cat-pinterest-api
    build:
      context: ./api/
    ports:
      - "3000:3000"
    networks:
      - cat-pinterest-net
    environment:
      NODE_ENV: prod
      POSTGRES_HOST: cat-pinterest-api-pg
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: cat-pinterest
      API_KEY: live_Bh0aMNugpoe8rU7o8api8ey5x3RVMx5aqWmruBIQX4QlbxWguGC7hKEM3KdlvQR5
    depends_on:
      cat-pinterest-api-pg:
        condition: service_healthy

  cat-pinterest-front:
    container_name: cat-pinterest-front
    image: cat-pinterest-front
    build:
      context: ./front/
    networks:
      - cat-pinterest-net
    environment:
      NODE_ENV: prod
      VITE_API_URL: cat-pinterest-api

  cat-pinterest-api-pg:
    container_name: cat-pinterest-api-pg
    image: postgres:14
    networks:
      - cat-pinterest-net
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: cat-pinterest
    #      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10

networks:
  cat-pinterest-net: